#!/bin/bash
#
# ugreen-idx6011-pro / calibrate.sh
#
# One-time interactive bay->LED calibration. No code editing required.
# Lights each of the 6 bay LEDs top-to-bottom; you say which installed disk is in it.
# Writes the result to mapping.conf, which the monitor reads (overriding the built-in default).
#
# Run it in a terminal on the NAS:  bash /boot/config/plugins/ugreen-idx6011-pro/calibrate.sh
#
set -u
BIN=/usr/local/bin/ugreen_leds_cli
export UGREEN_MODEL=idx6011
CONF=/boot/config/plugins/ugreen-idx6011-pro/mapping.conf

[ -x "$BIN" ] || { echo "ERROR: $BIN not found — is the plugin installed?"; exit 1; }

port_of(){ readlink -f /sys/block/"$1"/device 2>/dev/null | grep -oE '0000:[0-9a-f]{2}:[0-9a-f]{2}\.[0-9]/ata[0-9]+'; }

# collect present SATA disks
mapfile -t ROWS < <(lsblk -Sndo name,tran,size,serial 2>/dev/null | awk '$2=="sata"{print $1"|"$3"|"$4}')
[ ${#ROWS[@]} -gt 0 ] || { echo "No SATA disks detected — insert disks first."; exit 1; }

echo "=== UGREEN iDX6011 Pro — LED bay calibration ==="
echo
echo "Installed disks:"
i=1
declare -a DEV PORT
for r in "${ROWS[@]}"; do
  IFS='|' read -r name size serial <<< "$r"
  p=$(port_of "$name")
  DEV[$i]="$name"; PORT[$i]="$p"
  printf "  [%d] /dev/%-4s  %-7s  serial=%-16s  port=%s\n" "$i" "$name" "$size" "$serial" "$p"
  i=$((i+1))
done
echo "  [0] empty bay / skip"
echo
echo "I'll light each bay LED (top=1 .. bottom=6). For each, type the number of the disk that's in it."
echo

# stop the monitor daemon so it doesn't repaint the LEDs during calibration
[ -f /run/ugreen-leds.pid ] && kill "$(cat /run/ugreen-leds.pid)" 2>/dev/null
sleep 1

for n in 1 2 3 4 5 6; do "$BIN" disk$n -off >/dev/null 2>&1; done

declare -A MAP
for n in 1 2 3 4 5 6; do
  "$BIN" disk$n -on -color 255 255 255 -brightness 220 >/dev/null 2>&1
  read -rp "  Bay LED #$n is WHITE now — which disk is in it? [0-$(( ${#ROWS[@]} ))]: " sel
  "$BIN" disk$n -off >/dev/null 2>&1
  if [[ "$sel" =~ ^[0-9]+$ ]] && [ "$sel" -ge 1 ] && [ "$sel" -le "${#ROWS[@]}" ] && [ -n "${PORT[$sel]}" ]; then
    MAP["${PORT[$sel]}"]=$n
    echo "     -> bay $n = /dev/${DEV[$sel]} (port ${PORT[$sel]})"
  fi
done

mkdir -p "$(dirname "$CONF")"
{
  echo "# ugreen-idx6011-pro bay mapping: '<pci>/ataN <bay>'. Generated by calibrate.sh."
  for p in "${!MAP[@]}"; do echo "$p ${MAP[$p]}"; done
} > "$CONF"

echo
echo "Saved $CONF:"
cat "$CONF"
echo
# The monitor re-reads mapping.conf live (~2s). Only (re)start it if it isn't already running.
if [ -f /run/ugreen-leds.pid ] && kill -0 "$(cat /run/ugreen-leds.pid 2>/dev/null)" 2>/dev/null; then
  echo "Applied — the running monitor will update the front-panel LEDs within a couple of seconds."
else
  echo "Starting the LED monitor..."
  ( setsid /usr/local/bin/ugreen-idx6011-monitor >/var/log/ugreen-leds-monitor.log 2>&1 </dev/null & )
  echo "Done — the front-panel LEDs now follow your bays."
fi
